url: "https://wolfman30.github.io"
baseurl: "/ai-twin-prompts"   # because this is a project site
collections:
  prompts:
    output: true
    permalink: /prompts/:name/

# https://wolfman30.github.io/ai-twin-prompts/prompts/

